# Generated by Django 4.1.5 on 2023-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=122)),
                ("email", models.CharField(default="", max_length=122)),
                ("subject", models.CharField(default="", max_length=12)),
                ("message", models.CharField(default="", max_length=12)),
                ("date", models.DateField(verbose_name="date published")),
            ],
        ),
    ]
