# Generated by Django 4.1.5 on 2023-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(default="", max_length=455),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="", max_length=233),
        ),
    ]
